{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "4.0.0-alpha-09",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0-alpha-09.aar",
          "url": "autoussd-sdk-4.0.0-alpha-09.aar",
          "size": 946489,
          "sha512": "0d0abdd1de24d25676838b20813f1736974456a799ac028351db69f0e6692529a4f9b357585ad971da4cc712b8158af3a88c85f0418c58bcfe4a19ac65c2939c",
          "sha256": "bb1868a299107070a998096c86426e6fcf60ad643f8310455acfa3a1df9cd7a4",
          "sha1": "f1203dfe4bb1eedc3e78d2062af2a342a48372f5",
          "md5": "655a13bcd09f9bd02ce3679995723555"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0-alpha-09.aar",
          "url": "autoussd-sdk-4.0.0-alpha-09.aar",
          "size": 946489,
          "sha512": "0d0abdd1de24d25676838b20813f1736974456a799ac028351db69f0e6692529a4f9b357585ad971da4cc712b8158af3a88c85f0418c58bcfe4a19ac65c2939c",
          "sha256": "bb1868a299107070a998096c86426e6fcf60ad643f8310455acfa3a1df9cd7a4",
          "sha1": "f1203dfe4bb1eedc3e78d2062af2a342a48372f5",
          "md5": "655a13bcd09f9bd02ce3679995723555"
        }
      ]
    }
  ]
}
