{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "4.0.0-alpha-05",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0-alpha-05.aar",
          "url": "autoussd-sdk-4.0.0-alpha-05.aar",
          "size": 946357,
          "sha512": "fe07023ded5f35c51015020f9c5e0a5742a8a68971632005ad69898b0adb08e792d04c3b396e59a34b2f2a91b2793268a6594c6b98e885aa09261d8da14e2b35",
          "sha256": "03aa9bba6a15c1f201cefeedc4a1097f23ce399f42cf4d3f5f84725a8c1438d1",
          "sha1": "6c704c540ffe80a15a1e39cc38d63bc8e4164b4e",
          "md5": "a96b63f41a033ac7f2ba2ffc6d034389"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0-alpha-05.aar",
          "url": "autoussd-sdk-4.0.0-alpha-05.aar",
          "size": 946357,
          "sha512": "fe07023ded5f35c51015020f9c5e0a5742a8a68971632005ad69898b0adb08e792d04c3b396e59a34b2f2a91b2793268a6594c6b98e885aa09261d8da14e2b35",
          "sha256": "03aa9bba6a15c1f201cefeedc4a1097f23ce399f42cf4d3f5f84725a8c1438d1",
          "sha1": "6c704c540ffe80a15a1e39cc38d63bc8e4164b4e",
          "md5": "a96b63f41a033ac7f2ba2ffc6d034389"
        }
      ]
    }
  ]
}
