{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "3.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.0.0.aar",
          "url": "autoussd-sdk-3.0.0.aar",
          "size": 217789,
          "sha512": "d0f68127d741f6157b59b0c67b9d96d722a5e859e3260d0c5918f7bd8c9857e7d9df79bee248d71686ccb17f968d833d7309717a0549e5b736e5117a361c31f8",
          "sha256": "04ab6e58253230a5af684b8c6c7b86e9cfc310fa8ea4078b62d441e28b1ff111",
          "sha1": "b1048e84a8093410021c82aeab304c0a0dc6d68d",
          "md5": "daa0f2e1e6cc6a8568db5b5f392f411d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.0.0.aar",
          "url": "autoussd-sdk-3.0.0.aar",
          "size": 217789,
          "sha512": "d0f68127d741f6157b59b0c67b9d96d722a5e859e3260d0c5918f7bd8c9857e7d9df79bee248d71686ccb17f968d833d7309717a0549e5b736e5117a361c31f8",
          "sha256": "04ab6e58253230a5af684b8c6c7b86e9cfc310fa8ea4078b62d441e28b1ff111",
          "sha1": "b1048e84a8093410021c82aeab304c0a0dc6d68d",
          "md5": "daa0f2e1e6cc6a8568db5b5f392f411d"
        }
      ]
    }
  ]
}
