{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "4.0.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0.aar",
          "url": "autoussd-sdk-4.0.0.aar",
          "size": 946461,
          "sha512": "29dde8e71866b6dc7a0c9ac8f2bf1e66f07049a427ca17c284ac4c58bf89cb774cea73da6f0f68fc54092d4274093fea857aae58aa652d918892ae461ca6b81b",
          "sha256": "aba95fb42e2d482e3c6ffdb279589c87fda32d194e021e56eaf869aac3f293b9",
          "sha1": "27b2b07484834d0cfdd009db08102d1d5f40d698",
          "md5": "ee4df7c195f320c0586d409b269676ea"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0.aar",
          "url": "autoussd-sdk-4.0.0.aar",
          "size": 946461,
          "sha512": "29dde8e71866b6dc7a0c9ac8f2bf1e66f07049a427ca17c284ac4c58bf89cb774cea73da6f0f68fc54092d4274093fea857aae58aa652d918892ae461ca6b81b",
          "sha256": "aba95fb42e2d482e3c6ffdb279589c87fda32d194e021e56eaf869aac3f293b9",
          "sha1": "27b2b07484834d0cfdd009db08102d1d5f40d698",
          "md5": "ee4df7c195f320c0586d409b269676ea"
        }
      ]
    }
  ]
}
