{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "3.0.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.0.2.aar",
          "url": "autoussd-sdk-3.0.2.aar",
          "size": 218365,
          "sha512": "584b1ac5c3c127f6af88dc818c0d6cc4d32dfbb6fc8a8c7f3389b913f2f923eb575d6b411c7133ed99874290829be2f4c6ff01a00a0fbe5d79d2aa8c9c666021",
          "sha256": "fd63d4019bd54836375961290b4da1708ea2f823163c3abdd3a9772338698153",
          "sha1": "b2c5941bc0c3aa59a23f8d804e068001257acc2c",
          "md5": "a2e2cb70ae16d13bc11a7a196f3a426d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.0.2.aar",
          "url": "autoussd-sdk-3.0.2.aar",
          "size": 218365,
          "sha512": "584b1ac5c3c127f6af88dc818c0d6cc4d32dfbb6fc8a8c7f3389b913f2f923eb575d6b411c7133ed99874290829be2f4c6ff01a00a0fbe5d79d2aa8c9c666021",
          "sha256": "fd63d4019bd54836375961290b4da1708ea2f823163c3abdd3a9772338698153",
          "sha1": "b2c5941bc0c3aa59a23f8d804e068001257acc2c",
          "md5": "a2e2cb70ae16d13bc11a7a196f3a426d"
        }
      ]
    }
  ]
}
