{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "3.0.0-alpha-01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.0.0-alpha-01.aar",
          "url": "autoussd-sdk-3.0.0-alpha-01.aar",
          "size": 217682,
          "sha512": "cecaa7cfe5bbe6910d59d11b4f5b6ff5a5fa395eb66adbcf9ea4de740a8740f7bf06a4f156c962dbd8c90e2118d12ba1c399e1d98c9ec7226c52d396582a33e3",
          "sha256": "7eaa4e23ae445baf7c8d2b7a5874b30bae1cf577f9e0360544b249f8cc473977",
          "sha1": "0dc11cf3df4a44e5682d21363efaf6876635f987",
          "md5": "344e09ad3be8970628eb47722a040bf9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.0.0-alpha-01.aar",
          "url": "autoussd-sdk-3.0.0-alpha-01.aar",
          "size": 217682,
          "sha512": "cecaa7cfe5bbe6910d59d11b4f5b6ff5a5fa395eb66adbcf9ea4de740a8740f7bf06a4f156c962dbd8c90e2118d12ba1c399e1d98c9ec7226c52d396582a33e3",
          "sha256": "7eaa4e23ae445baf7c8d2b7a5874b30bae1cf577f9e0360544b249f8cc473977",
          "sha1": "0dc11cf3df4a44e5682d21363efaf6876635f987",
          "md5": "344e09ad3be8970628eb47722a040bf9"
        }
      ]
    }
  ]
}
