{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "4.0.0-alpha-06",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0-alpha-06.aar",
          "url": "autoussd-sdk-4.0.0-alpha-06.aar",
          "size": 946704,
          "sha512": "33e71386a0c214075e6ad5a2efb017bb013ff43dddbec589367791cd13a8b7d996866cf24b0013db4dfe1b050d6a08af7dc8e830c4c1f7cca7740fde4639ad8d",
          "sha256": "5736381f5920dda9d45cc49558440fd30efcd37e28d10eb0ebf86ac1729e0c8c",
          "sha1": "f77643b76d5be26fc37504b35f1df7ec715bdb80",
          "md5": "8f1f1bf9e7275b71eddeec67ef15091d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0-alpha-06.aar",
          "url": "autoussd-sdk-4.0.0-alpha-06.aar",
          "size": 946704,
          "sha512": "33e71386a0c214075e6ad5a2efb017bb013ff43dddbec589367791cd13a8b7d996866cf24b0013db4dfe1b050d6a08af7dc8e830c4c1f7cca7740fde4639ad8d",
          "sha256": "5736381f5920dda9d45cc49558440fd30efcd37e28d10eb0ebf86ac1729e0c8c",
          "sha1": "f77643b76d5be26fc37504b35f1df7ec715bdb80",
          "md5": "8f1f1bf9e7275b71eddeec67ef15091d"
        }
      ]
    }
  ]
}
