{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "3.0.0-alpha-02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.0.0-alpha-02.aar",
          "url": "autoussd-sdk-3.0.0-alpha-02.aar",
          "size": 217729,
          "sha512": "7ace7e82967341deb8dcce3f95351872d056ad6d078ded17d037772970df628552504f291963d018ed4afe82a5522feb4d7c801087961bf06bcd7e4f44eb91c8",
          "sha256": "1dc04e1ba15b406165709d2117744254bdc3360680ef8014e5438342bc0f7cc9",
          "sha1": "60a94484169c0a2fa512cbb596fcad9c15f2ab19",
          "md5": "188fae46e15954c55dbd66f0b9cc5ee4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.0.0-alpha-02.aar",
          "url": "autoussd-sdk-3.0.0-alpha-02.aar",
          "size": 217729,
          "sha512": "7ace7e82967341deb8dcce3f95351872d056ad6d078ded17d037772970df628552504f291963d018ed4afe82a5522feb4d7c801087961bf06bcd7e4f44eb91c8",
          "sha256": "1dc04e1ba15b406165709d2117744254bdc3360680ef8014e5438342bc0f7cc9",
          "sha1": "60a94484169c0a2fa512cbb596fcad9c15f2ab19",
          "md5": "188fae46e15954c55dbd66f0b9cc5ee4"
        }
      ]
    }
  ]
}
