{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "4.0.0-alpha-02",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0-alpha-02.aar",
          "url": "autoussd-sdk-4.0.0-alpha-02.aar",
          "size": 167942,
          "sha512": "0577febda168893051ea821715a8d63701fee4a2a716d7965509c0db71bea324f4e0eefd9c802508a4b6cf928de997def9991a2bc9079f06382192715fda7723",
          "sha256": "695cde73cae6f1114cb93034a112fed2f1cb78d5166437cea2f435f9b7fd6b55",
          "sha1": "0e00a309c48ece34cdb5421731f27d5a4555eb7d",
          "md5": "753b8c384355c0afa38c4f1244bc426b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.0.0-alpha-02.aar",
          "url": "autoussd-sdk-4.0.0-alpha-02.aar",
          "size": 167942,
          "sha512": "0577febda168893051ea821715a8d63701fee4a2a716d7965509c0db71bea324f4e0eefd9c802508a4b6cf928de997def9991a2bc9079f06382192715fda7723",
          "sha256": "695cde73cae6f1114cb93034a112fed2f1cb78d5166437cea2f435f9b7fd6b55",
          "sha1": "0e00a309c48ece34cdb5421731f27d5a4555eb7d",
          "md5": "753b8c384355c0afa38c4f1244bc426b"
        }
      ]
    }
  ]
}
