{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "3.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.1.0.aar",
          "url": "autoussd-sdk-3.1.0.aar",
          "size": 228715,
          "sha512": "0138ee5f73acc832f50b167903ad6ff5c3b2a29910e3bcbe47d5271b430df90b0e50fad96a7b62b58e521d3e68e4bdfee47ae52f8c6848d8d6b07c9176717193",
          "sha256": "6ae91c7a5e7a83a151f39ad3742a27009c3f07785c47f29eb0f058141b71e9d4",
          "sha1": "07ff2d9cddb96b66f6079ed6f1a9ef5cb12035ae",
          "md5": "a9744e5eec4233fecae3224b7de38703"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.1.0.aar",
          "url": "autoussd-sdk-3.1.0.aar",
          "size": 228715,
          "sha512": "0138ee5f73acc832f50b167903ad6ff5c3b2a29910e3bcbe47d5271b430df90b0e50fad96a7b62b58e521d3e68e4bdfee47ae52f8c6848d8d6b07c9176717193",
          "sha256": "6ae91c7a5e7a83a151f39ad3742a27009c3f07785c47f29eb0f058141b71e9d4",
          "sha1": "07ff2d9cddb96b66f6079ed6f1a9ef5cb12035ae",
          "md5": "a9744e5eec4233fecae3224b7de38703"
        }
      ]
    }
  ]
}
