{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "3.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.1.1.aar",
          "url": "autoussd-sdk-3.1.1.aar",
          "size": 229585,
          "sha512": "7574a2e0a176b6aaf546c9313aa4399d750162d33298c897487b84c9cbda48f3f3874cdbf8eaffa577f76867d8aed439bc337cb1e9a71b04b962cea4fb862e47",
          "sha256": "d749fa1df2603c7db4dc1e9ca4f24c7ae138984b04c46b75a941b84c0821e121",
          "sha1": "fde7b1f731b8c3525a7d28cd26fb9996bf7ca0f4",
          "md5": "9c0f5538935a3007986c65c5c97bdacf"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.5.20"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.7.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.3"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-3.1.1.aar",
          "url": "autoussd-sdk-3.1.1.aar",
          "size": 229585,
          "sha512": "7574a2e0a176b6aaf546c9313aa4399d750162d33298c897487b84c9cbda48f3f3874cdbf8eaffa577f76867d8aed439bc337cb1e9a71b04b962cea4fb862e47",
          "sha256": "d749fa1df2603c7db4dc1e9ca4f24c7ae138984b04c46b75a941b84c0821e121",
          "sha1": "fde7b1f731b8c3525a7d28cd26fb9996bf7ca0f4",
          "md5": "9c0f5538935a3007986c65c5c97bdacf"
        }
      ]
    }
  ]
}
