{
  "formatVersion": "1.1",
  "component": {
    "group": "com.autoussd",
    "module": "autoussd-sdk",
    "version": "4.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.2.0.aar",
          "url": "autoussd-sdk-4.2.0.aar",
          "size": 950775,
          "sha512": "ea903d455ceb5b6eee0243c7e24d4397ea61ec842f612faa678c82c14ecdb4b6cd27b3a3a973b88333759855b37723b82e61a4deb1888f96f885b25c769855c7",
          "sha256": "f7ed6c59ae295f58b16f171c74543791b6ac20d5cdeec9177512ddadd2f76f7a",
          "sha1": "7a3164ac79bacbd9620da9683c7669bfdc4b0d7a",
          "md5": "7e330f4f7d01c793fc4b615dc73db627"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.21"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.8.0"
          }
        },
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "com.google.android.material",
          "module": "material",
          "version": {
            "requires": "1.6.1"
          }
        },
        {
          "group": "androidx.constraintlayout",
          "module": "constraintlayout",
          "version": {
            "requires": "2.1.4"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity-ktx",
          "version": {
            "requires": "1.4.0"
          }
        },
        {
          "group": "androidx.fragment",
          "module": "fragment-ktx",
          "version": {
            "requires": "1.4.1"
          }
        },
        {
          "group": "androidx.room",
          "module": "room-runtime",
          "version": {
            "requires": "2.4.2"
          }
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.gridlayout",
          "module": "gridlayout",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "io.socket",
          "module": "socket.io-client",
          "version": {
            "requires": "2.0.0"
          },
          "excludes": [
            {
              "group": "org.json",
              "module": "json"
            }
          ]
        },
        {
          "group": "org.greenrobot",
          "module": "eventbus",
          "version": {
            "requires": "3.3.1"
          }
        }
      ],
      "files": [
        {
          "name": "autoussd-sdk-4.2.0.aar",
          "url": "autoussd-sdk-4.2.0.aar",
          "size": 950775,
          "sha512": "ea903d455ceb5b6eee0243c7e24d4397ea61ec842f612faa678c82c14ecdb4b6cd27b3a3a973b88333759855b37723b82e61a4deb1888f96f885b25c769855c7",
          "sha256": "f7ed6c59ae295f58b16f171c74543791b6ac20d5cdeec9177512ddadd2f76f7a",
          "sha1": "7a3164ac79bacbd9620da9683c7669bfdc4b0d7a",
          "md5": "7e330f4f7d01c793fc4b615dc73db627"
        }
      ]
    }
  ]
}
